apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: default
data:
  master.conf: |
    port 6379
    appendonly yes
    bind 0.0.0.0

  replica.conf: |
    port 6379
    replicaof redis-master-service 6379
    appendonly yes
  
  sentinel.conf: |
    port 26379
    sentinel monitor mymaster redis-master-service 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel resolve-hostnames yes
    sentinel failover-timeout mymaster 10000
    bind 0.0.0.0
