apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: redis-sentinel
  ports:
    - port: 26379
      targetPort: 26379
      nodePort: 30079